# Titanic Survival Analysis
### Python Data Cleaning + Exploratory Data Analysis

Objective:
Analyze Titanic passenger data to identify major factors affecting survival using data cleaning, feature engineering, and exploratory data analysis.

In [33]:
import numpy as np
import pandas as pd

In [34]:
df = pd.read_csv(r"Titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [35]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [36]:
df.drop(columns="Cabin",inplace=True)

In [37]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [38]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [58]:
df["Embarked"] = df["Embarked"].map({
    "C": "Cherbourg",
    "Q": "Queenstown",
    "S": "Southampton"
})

In [39]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [40]:
df.duplicated().sum()

0

In [41]:
df["Title"] = df["Name"].str.extract(" ([A-Za-z]+)\.",expand=False)

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\Sarvesh\AppData\Local\Temp\ipykernel_28820\3172556064.py:1: SyntaxWarning: invalid escape sequence '\.'
  df["Title"] = df["Name"].str.extract(" ([A-Za-z]+)\.",expand=False)

In [42]:
df.drop(columns="Name",inplace=True)

In [43]:
df["TicketPrefix"] = df["Ticket"].str.extract(r'([A-Za-z./ ]+)', expand=False)

In [44]:
df["TicketPrefix"] = df["TicketPrefix"].fillna("Numeric")

In [45]:
df.groupby("Sex")["Survived"].mean()*100

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [46]:
df.groupby("Pclass")["Survived"].mean()*100

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

In [47]:
df["Ticket_Class"] = np.where(df["Fare"] > 100 ,"Luxury",np.where(df["Fare"] > 50,"Premium","General"))

In [48]:
df.groupby("Ticket_Class")["Survived"].mean()*100

Ticket_Class
General    31.874145
Luxury     73.584906
Premium    65.420561
Name: Survived, dtype: float64

In [49]:
df.drop(columns="Ticket_Class")

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Title,TicketPrefix
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,S,Mr,A/
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C,Mrs,PC
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S,Miss,STON/O
3,4,1,1,female,35.0,1,0,113803,53.1000,S,Mrs,Numeric
4,5,0,3,male,35.0,0,0,373450,8.0500,S,Mr,Numeric
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,13.0000,S,Rev,Numeric
887,888,1,1,female,19.0,0,0,112053,30.0000,S,Miss,Numeric
888,889,0,3,female,28.0,1,2,W./C. 6607,23.4500,S,Miss,W./C.
889,890,1,1,male,26.0,0,0,111369,30.0000,C,Mr,Numeric
890,891,0,3,male,32.0,0,0,370376,7.7500,Q,Mr,Numeric

In [50]:
df.groupby(["Pclass","Sex"])["Survived"].mean().unstack(fill_value=0)*100

Sex        female       male
Pclass
1       96.808511  36.885246
2       92.105263  15.740741
3       50.000000  13.544669

In [51]:
df.groupby("Embarked")["Survived"].mean()*100

Embarked
C    55.357143
Q    38.961039
S    33.900929
Name: Survived, dtype: float64

In [57]:
df.to_excel("Titanic_cleaned.xlsx", index=False)

## Key Insights
- Female passengers had higher survival rates
- First-class passengers had better survival chances
- First-class females had highest survival probability
- Third-class males had lowest survival probability
- Higher fare passengers survived more frequently
- Small family groups showed better survival outcomes